DATA SEGMENT
  ARRAY1 DB 11H,22H,33H,44H,55H,66H,77H,88H,99H,AAH;
  ARRAY2 DB 66H,77H,88H,99H,AAH,11H,22H,33H,44H,55H;
  COUNT DB 0AH 
DATA ENDS

CODE SEGMENT
  ASSUME CS:CODE,DS:DATA
  
START:
  MOV AX,DATA
  MOV DS,AX
  
  LEA SI,ARRAY1; Load SI with EA of ARRAY1 in ds
  LEA DI,ARRAY2; Load DI with EA of ARRAY2 in ds

  MOV CH, 00H
  MOV CL,COUNT

NEXT:
  MOV AL,[SI]
  MOV AH,[DI]
  MOV [SI],AH
  MOV [DI],AL
  INC SI
  INC DI
  LOOP NEXT
  
  MOV AH,4CH
  INT 21H

CODE ENDS
END START